* Non-ambiguous annotations

Training the classifier on non-ambiguous annotations:

|Corpus|Number of annotations|
|EMEA|468402|
|Medline|5152543|

** Annotation counts

|N|Group|*EMEA*|Percent|*Medline*|Percent|
|1|ANAT|31531|7%|618274|12%|
|2|PHYS|25074|5%|319140|6%|
|3|DEVI|12124|3%|66772|1%|
|4|PHEN|10120|2%|113796|2%|
|5|OBJC|20440|4%|223999|4%|
|6|LIVB|65222|14%|661970|13%|
|7|CHEM|135813|29%|536262|10%|
|8|PROC|70094|15%|1162085|23%|
|9|GEOG|7101|2%|79592|2%|
|10|DISO|90883|19%|1370653|27%|
||Total|468402|100%|5152543|100%|

* Classifiers

** Error rates

Percentage of errors over the test set

|Classifier|CV folds|Error rate *EMEA*|Error rate *Medline*|
|Constant fit (theoretic)||71%|73%|
|VeryVeryNaiveBayes|10|58.7%|63.8%|
|NaiveBayesContextRestricted (window size=4)|10|47.0%|59.0%|
|NaiveBayesContextRestricted (window size=3)|10|45.0%|57.5%|
|NaiveBayesContextRestricted (window size=2)|10|43.7%|57.2%|
|NaiveBayesContextRestricted (window size=1)|10|49.0%|55.4%|

Theoretic contant fit - always predict the most numerous class.

* Agreement MTurk vs. Classifier

** VeryVeryNaiveBayes

Data from Mechanical Turk was imported: annotations with agreement larger than a threshold were considered. Classifiers were trained on EMEA and Medline to predict groups of these annotations. Below are percentages of annotations for which labels predicted by MTurk and classifiers match.

|Vote agreement threshold|Total votes|Classifier trained on *EMEA*|Classifier trained on *Medline*|
|50%|170|||
|60%|169|11.8%|22.48%|
|65%|169|||
|70%|60|25.0%|25.0%|
|75%|49|30.1%|26.5%|
|99%|48|||

The result with the largest agreement was analyzed by hand, see [[http://davtyan.org/pml/mturk-vs-classifier-0.75-emea.xlsx][the annotated table]]. Subjectively, in conflicts MTurk is mostly right and the classifier is mostly wrong. The classifier should be tweaked to increase the agreement.

* Agreement MTurk vs. Expert

About 200 instances were hand-annotated by an expert and compared with MTurk votes. The comparison table can be downloaded [[http://davtyan.org/pml/mturk_expert_comparison.xlsx][here]]. In the table, result `NONE` for Mechanical Turk means eigher `None of the above` or `I don't know` replies.

|Cases|Agreement|
|All cases|61%|
|Where MTurk majority vote is meaningful|76%|
|Where both votes are meaningful|81%|

By meaningful vote here we mean not `None of the above` and not `I don't know`.